language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
install:
  - gem install rdiscount
  - gem install json
  - gem install parallel
  - gem install rkelly-remix -v 0.0.1
  - gem install rspec
  - gem install rake
  - gem install dimensions
